# Set theme
theme: alembic-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'American International Rattlesnake Museum'
description: >- # this means to ignore newlines until "baseurl:"
  The Rattlesnake Museum is an exciting and educational experience for the
  entire family. This animal conservation museum reveals the hundreds of ways
  that rattlesnakes and other "less desirable" animals have influenced our
  lives. Examples are given through artifacts, memorabilia, and the largest
  collection of different species of live rattlesnakes in the world.
permalink: pretty
#logo: "/assets/uploads/logo_tab.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog
    feature_image: "https://picsum.photos/2560/600?image=866"
  animals:
    name: animals
    title: "Exhibit Animals"
    output: true
    create: true
    description: "Animals in the Museum"
  items:
    name: items
    title: "Exhibit Items"
    output: true
    create: true
